"""Parameter explanations shared by the configuration UI."""

PARAMETER_DESCRIPTIONS = {
    "chroma_directory": "Chroma 本地索引存储目录。",
    "chroma_collection": "Chroma 集合基础名称，各知识库使用独立集合。",
    "source_directory": "原始上传文件及解析记录的归档目录。",
    "knowledge_base_directory": "知识库注册信息、索引状态与恢复档案目录。",
    "embedding_dimensions": "嵌入向量维度，必须与模型输出和索引一致；修改后需检查并重建索引。",
    "embedding_mode": "嵌入实现：hash 为本地确定性基线，compatible 为远程兼容接口，sentence_transformers 为本地模型；auto 按配置选择。",
    "embedding_model": "嵌入模型名称或本地模型路径。",
    "embedding_model_revision": "本地模型版本或提交标识，用于固定模型与索引身份。",
    "embedding_base_url": "远程嵌入 API 基础地址。",
    "embedding_batch_size": "每批嵌入的文本数量；需符合供应商批量限制。",
    "embedding_request_timeout": "远程嵌入请求超时，单位秒。",
    "embedding_send_dimensions": "是否向远程嵌入接口显式传递维度参数。",
    "embedding_device": "本地嵌入计算设备，例如 cpu 或 cuda。",
    "embedding_local_files_only": "本地嵌入是否仅加载缓存模型，避免自动下载。",
    "embedding_normalize": "是否对本地嵌入向量执行归一化。",
    "embedding_query_prefix": "仅添加到查询文本前的模型指令前缀。",
    "embedding_document_prefix": "仅添加到入库文本前的模型指令前缀。",
    "vector_backend": "向量存储实现，可选择 Chroma 或 Qdrant。",
    "qdrant_directory": "Qdrant 本地持久化目录。",
    "qdrant_collection": "Qdrant 集合基础名称，各知识库隔离存储。",
    "chunker_mode": "分块算法实现，例如字符分块或递归分块。",
    "chunk_size": "分块目标大小，单位字符。",
    "chunk_overlap": "相邻分块重叠字符数，必须小于 chunk_size。",
    "fusion_mode": "多路召回融合算法：rrf 按排名融合，weighted_sum 按归一化分数加权。",
    "fusion_weights": "融合权重 JSON 对象，键为召回路名称（例如 vector、keyword）；权重必须非负且有限。",
    "fusion_normalization": "加权融合分数归一化方式，目前为 min_max。",
    "fusion_rank_constant": "RRF 排名平滑常数；留空时使用 rrf_rank_constant。",
    "default_retrieval_strategy": "规划器关闭时使用的固定检索策略：向量、关键词或混合。",
    "default_retrieval_rerank": "规划器关闭时是否启用重排；仍需配置有效的重排服务。",
    "reranker_mode": "重排模式：disabled 关闭，cross_encoder 本地，cloud 云端，auto 按配置选择并允许故障降级。",
    "reranker_model": "本地 CrossEncoder 模型名称或路径。",
    "reranker_device": "本地重排计算设备，例如 cpu 或 cuda。",
    "reranker_batch_size": "本地重排每批处理的候选数。",
    "reranker_candidate_k": "重排候选预算，可大于最终 top_k；重排后仍按最终检索上限截取。",
    "reranker_local_files_only": "本地重排是否只使用已缓存模型。",
    "reranker_cloud_protocol": "云端重排接口协议：DashScope 或兼容协议。",
    "reranker_cloud_model": "云端重排模型名称，例如 gte-rerank-v2。",
    "reranker_cloud_url": "云端重排完整请求地址。",
    "reranker_cloud_timeout": "云端重排请求超时，单位秒。",
    "reranker_cloud_instruct": "可选的重排任务指令；是否支持取决于模型和协议。",
    "query_planner_mode": "disabled 固定策略，heuristic 规则规划，llm 模型规划，auto 在模型不可用时使用规则。",
    "planner_model": "查询分类、策略选择与改写使用的模型。",
    "planner_base_url": "规划模型的 OpenAI 兼容 API 基础地址。",
    "planner_temperature": "规划模型采样温度，越低通常越稳定。",
    "planner_request_timeout": "规划模型单次请求超时，单位秒。",
    "planner_max_retries": "规划模型请求失败后的最大重试次数。",
    "planner_minimum_confidence": "规划置信度阈值；低于阈值时采用安全的混合检索策略。",
    "planner_max_rewrites": "规划器最多保留的改写查询数量；0 表示不保留改写。",
    "answer_generator_mode": "extractive 展示检索证据，llm 使用生成模型，auto 在生成异常时降级。",
    "generation_model": "检索后生成回答的模型；未设置时按生成工厂的回退配置选择。",
    "generation_system_prompt": "生成系统提示词，定义回答规则、证据约束与引用要求。",
    "generation_user_prompt": "生成用户模板；必须包含 {context} 与 {question}，可选 {history}；字面花括号用 {{ 和 }}。",
    "generation_base_url": "回答生成模型的 OpenAI 兼容 API 基础地址。",
    "generation_temperature": "回答采样温度，较低值通常更稳定。",
    "generation_request_timeout": "生成模型请求超时，单位秒。",
    "generation_max_retries": "生成请求失败后的最大重试次数。",
    "generation_max_tokens": "模型输出 Token 预算；部分推理模型会将思考 Token 计入此预算。",
    "generation_max_context_chunks": "实际送入生成模型的最大 chunk 数；context_count 同时受此值与最终检索结果数限制。",
    "evaluation_concurrency": "评估任务最大并行数量，影响请求压力与运行耗时。",
    "evaluation_metrics": "逗号分隔的评估指标名称；留空使用默认指标集合。",
    "evaluation_report_limit": "读取评估报告列表时允许的最大数量。",
    "evaluation_report_directory": "评估报告持久化目录。",
    "evaluation_dataset_directory": "评估数据集存储目录。",
    "evaluation_dataset_max_cases": "单个评估数据集允许的最大案例数。",
    "evaluation_dataset_max_bytes": "单个评估数据集允许的最大文件大小，单位字节。",
    "evaluation_judge_mode": "heuristic 规则评估，llm 模型评估，auto 模型失败时降级。",
    "evaluation_judge_model": "用于评价生成答案的模型。",
    "evaluation_judge_base_url": "评估模型的 OpenAI 兼容 API 基础地址。",
    "evaluation_judge_temperature": "评估模型采样温度，低值有助于保持评分稳定。",
    "evaluation_judge_request_timeout": "评估模型请求超时，单位秒。",
    "evaluation_judge_max_retries": "评估模型请求失败后的最大重试次数。",
    "evaluation_judge_max_tokens": "评估模型最大输出 Token 数。",
    "evaluation_judge_max_context_characters": "传给评估模型的上下文字符预算。",
    "hybrid_candidate_multiplier": "混合检索每一路召回相对候选预算的扩张倍数；融合和重排后仍截取最终 top_k。",
    "rrf_rank_constant": "旧版 RRF 平滑常数；fusion_rank_constant 未设置时使用。",
    "keyword_backend": "关键词检索后端：memory 为内存 BM25，elasticsearch 为 Elasticsearch。",
    "elasticsearch_url": "Elasticsearch 服务基础地址。",
    "elasticsearch_index": "关键词索引基础名称，各知识库使用独立索引。",
    "elasticsearch_username": "Elasticsearch 基础认证用户名。",
    "elasticsearch_verify_certs": "是否验证 Elasticsearch HTTPS 证书。",
    "elasticsearch_request_timeout": "Elasticsearch 请求超时，单位秒。",
    "elasticsearch_analyzer": "索引文本分词器；修改需重新建立关键词索引以保持分词一致。",
    "elasticsearch_bm25_k1": "BM25 词频饱和参数，控制词频对得分的影响。",
    "elasticsearch_bm25_b": "BM25 文档长度归一化参数，0 不归一化，1 完全归一化。"
}
